<a href="https://colab.research.google.com/github/Soil-labs/Research-ML-knowledge-maping/blob/main/map_knowledgeGraph_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://openai.com/blog/introducing-text-and-code-embeddings/

In [ ]:
!pip install openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 44 kB 1.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 147 kB 8.3 MB/s 
  Created wheel for openai: filename=openai-0.25.0-py3-none-any.whl size=55880 sha256=0d336e7d1c33d00d1e446351509094f69c812064522f7872b0cc0b228b956b97
  Stored in directory: /root/.cache/pip/wheels/4b/92/33/6f57c7aae0b16875267999a50570e81f15eecec577ebe05a2e
Successfully built openai


The **embedding is an information dense representation of the semantic meaning of a piece of text**. <br>
Each embedding is a vector of floating point numbers, such that the **distance between two embeddings in the vector space is correlated with semantic similarity between two inputs** in the original format. <br>
For example, if two texts are similar, then their vector representations should also be similar.

**Use cases:**

*   Text Similarity
*   Semantic Search
*   Classification
*   Clustering




1.   **Similarity embeddings** : These models are good at capturing semantic similarity between two or more pieces of text.
2.   **Text search embeddings**: These models help measure whether long documents are relevant to a short search query. There are two types: one for ***embedding the documents*** to be retrieved, and one for ***embedding the search query***.




In [ ]:
import pandas as pd
import openai, numpy as np
from openai.embeddings_utils import get_embedding, cosine_similarity

In [ ]:
api_key = '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'
openai.api_key = api_key


In [ ]:
# text_search = "I start coding today, I love working on javascript but I want to be more structure with neo4j and now I will start working with convolutional neural networks togehter with Figma" # design
# text_search = "Yesterday I start working for the first time with Figma and Canva, it is great adition to my skills, can't wait to spent more time with tools except photoshop" # front
# text_search = "Finally I start working with a user research, we are trying to uderstand better the users, " #product
# text_search = "my dad left me at the age of 3 and now I have a separation anxiety" #nothing
# text_search = "I went ot the art school for 9 years" #design
# text_search = "I am a retire marine corps, and I have served on the front" #nothing
# text_search = "I start building a website, at age 8 now I am in google" # design # FrontEnd
# text_search = "I start photography but now I want to focus on buidling for companies" # design 
text_search = "I finally learned how to work with node.js but also I want to focus more on react and angular" # FrontEnd
# text_search = "I start learning hw to design websites, I use photoshop and I start drawingm circles" #design
# text_search = "there was so much snow that the flight didn't land but after all we met with my family and it was fun" #nothing



question_ask = "Extract keywords from this text:\n\n" + text_search + "\n\n Result:"

response = openai.Completion.create(
  model="text-davinci-003",
  prompt=question_ask,
  temperature=0.5,
  max_tokens=60,
  top_p=1,
  frequency_penalty=0.8,
  presence_penalty=0
)



In [ ]:
print(response["choices"][0]["text"])

 
node.js, react, angular


<h3>Text Similarity</h3>

In [ ]:
# words_n = ["Neo4j","react","next.js","Figma","design","visual","graphic","art", "Javascript", "Coding" ,"CNN", "react","water","object","Convolutional Neural Networks","Machine Learning","cherry","pie"]
words_n = response["choices"][0]["text"].split(', ')
resp = openai.Embedding.create(
    input=words_n,
    engine="text-similarity-davinci-001")


# words_n_base = ["UI Design"]
words_n_base = ["Design","UX/UI","Graphic Design","Web Design","Game Design","Animation","General Design support from A-Z","NFT Design","Brand Design"]
resp_base = openai.Embedding.create(
    input=words_n_base,
    engine="text-similarity-davinci-001")


words_n_base_front = ["Frontend Developer","UI Implementation","Frontend Architecture","General Frontend Support","Web Development","App Development"]
resp_base_front = openai.Embedding.create(
    input=words_n_base_front,
    engine="text-similarity-davinci-001")


words_n_base_product = ["Product Manager","User Research","Market Research","Technical Team Coordination","Design Team Coordination","Ideation","Interviews"]
resp_base_product = openai.Embedding.create(
    input=words_n_base_product,
    engine="text-similarity-davinci-001")

In [ ]:
words_embed = []
for i in range(len( resp['data'])):
  words_embed.append(resp['data'][i]['embedding'])


words_embed_base = []
for i in range(len( resp_base['data'])):
  words_embed_base.append(resp_base['data'][i]['embedding'])


words_embed_base_front = []
for i in range(len( resp_base_front['data'])):
  words_embed_base_front.append(resp_base_front['data'][i]['embedding'])


words_embed_base_product = []
for i in range(len( resp_base_product['data'])):
  words_embed_base_product.append(resp_base_product['data'][i]['embedding'])


words_base_all = []
words_base_all.append(words_embed_base)
words_base_all.append(words_embed_base_front)
words_base_all.append(words_embed_base_product)

# print(words_base_all[1])
# print(words_embed_base_front)

[[-0.0020824233070015907, 0.010280277580022812, -0.0199124775826931, -0.010184971615672112, -0.008151790127158165, 0.01946771889925003, -0.0024970017839223146, -0.0024890596978366375, -0.0013723979936912656, -0.009505126625299454, -0.00409495597705245, 0.005298980977386236, 0.017320170998573303, 0.0005495945806615055, 0.003151432378217578, -0.004285566974431276, -0.008126375265419483, -0.006881050765514374, -0.018285932019352913, 0.0029226993210613728, -0.00066872633760795, -0.0015574493445456028, 0.014804108068346977, -0.004816100466996431, 0.013927297666668892, 0.006798452697694302, 0.015591965988278389, -0.0014287870144471526, -0.012497716583311558, -0.0005082955467514694, -0.012072019279003143, -0.003072011284530163, 0.0031768472399562597, -0.003618428949266672, -0.012828108854591846, 0.001926757744513452, 0.008355108089745045, -0.004739855881780386, 0.00046977627789601684, 0.01222450751811266, -0.00869185384362936, -0.0016789636574685574, -0.0004745415353681892, -0.006785745266824

In [ ]:
k = 10 # k best embeddings
emb_mat = np.stack(words_embed)
print(emb_mat)

emb_mat_base_all = []
for i in range(len(words_base_all)):
  emb_mat_base = np.stack(words_base_all[i])
  
  emb_mat_base_all.append(emb_mat_base)


emb_mat_base = np.stack(words_embed_base)
# print(emb_mat_base)


emb_mat_base_front = np.stack(words_embed_base_front)
# print(emb_mat_base_front)

emb_mat_base_product = np.stack(words_embed_base_product)
# print(emb_mat_base_product)


[[-0.0021859   0.01248091 -0.01345172 ... -0.01888317  0.00612307
  -0.00793144]
 [-0.01142295  0.00594349 -0.011709   ... -0.00711948  0.00590535
  -0.00480247]
 [-0.00813904  0.00794192 -0.01325137 ... -0.01439593  0.00853327
  -0.01025646]]
[[-0.01020377  0.01125145 -0.01212134 ... -0.00764489  0.0082735
  -0.00655911]
 [-0.00620065  0.01015459 -0.01282017 ... -0.00970398  0.00603564
  -0.0069432 ]
 [-0.00727952  0.00856153 -0.01810043 ... -0.01152538  0.01053531
  -0.00259575]
 ...
 [-0.00494679  0.0146943  -0.01101755 ... -0.00680739  0.00977292
  -0.00442607]
 [-0.00619265  0.01217581 -0.01312803 ... -0.00970002  0.01016978
  -0.00975715]
 [-0.00703361  0.00959418 -0.01151302 ... -0.00579463  0.00716069
  -0.00064729]]
[[-0.00208242  0.01028028 -0.01991248 ... -0.0156428   0.00461596
  -0.00103089]
 [-0.01355848  0.00829774 -0.01226871 ... -0.00753531  0.00782122
  -0.00478423]
 [-0.00665464  0.01353809 -0.01545757 ... -0.00952115  0.00348304
  -0.00493536]
 [-0.0070105   0.01112

In [ ]:
chooseWord = 3
scores = np.dot(emb_mat_base,emb_mat.T)
# scores = np.dot(emb_mat,emb_mat_base.T)
print(scores)


scores_base_all = []
for i in range(len(words_base_all)):
  scores_base = np.dot(emb_mat_base_all[i],emb_mat.T)
  
  scores_base_all.append(scores_base)


scores_front = np.dot(emb_mat_base_front,emb_mat.T)


print()
print()

print(scores_front)


scores_product = np.dot(emb_mat_base_product,emb_mat.T)


print()
print()

print(scores_product)

[[0.75857377 0.83413135 0.84073466]
 [0.78193644 0.80957474 0.80654613]
 [0.75240231 0.76632566 0.77401506]
 [0.79523176 0.78143967 0.78462498]
 [0.77616007 0.79309174 0.79554524]
 [0.77623766 0.83910064 0.83370238]
 [0.70976058 0.70269068 0.69631151]
 [0.76639109 0.78334828 0.78479009]
 [0.75755267 0.81195435 0.81021   ]]


[[0.81221858 0.7593976  0.76516075]
 [0.80072693 0.82349711 0.814047  ]
 [0.809166   0.77463429 0.78483933]
 [0.76918602 0.75809797 0.75549521]
 [0.83183232 0.77717363 0.77850659]
 [0.81495268 0.79219816 0.79277624]]


[[0.77425666 0.76122507 0.75931326]
 [0.78311655 0.79182359 0.77408148]
 [0.75735997 0.768469   0.76057961]
 [0.76225423 0.74977741 0.74845439]
 [0.74377232 0.7580191  0.75120024]
 [0.76509692 0.82028305 0.81322214]
 [0.76333957 0.7807444  0.78107812]]


In [ ]:
maxima = list(map(max, scores))
print(maxima)  # Output: [3, 6, 9]

maxima_base_all = []
for i in range(len(words_base_all)):
  maxima_base = list(map(max, scores_base_all[i]))
  
  maxima_base_all.append(maxima_base)


maxima_front = list(map(max, scores_front))
print(maxima_front)  # Output: [3, 6, 9]

maxima_product = list(map(max, scores_product))
print(maxima_product)  # Output: [3, 6, 9]


print(maxima_base_all)

[0.8407346583755813, 0.8095747369166394, 0.7740150565304874, 0.7952317639379396, 0.7955452379834044, 0.8391006399028276, 0.7097605774554672, 0.7847900934905462, 0.8119543463333635]
[0.8122185804643189, 0.823497107247265, 0.8091660030231081, 0.7691860170638556, 0.8318323222026065, 0.8149526782858767]
[0.774256656403223, 0.7918235880739435, 0.7684689978246045, 0.7622542291126118, 0.7580191047832017, 0.8202830457940575, 0.7810781169723617]
[[0.8407346583755813, 0.8095747369166394, 0.7740150565304874, 0.7952317639379396, 0.7955452379834044, 0.8391006399028276, 0.7097605774554672, 0.7847900934905462, 0.8119543463333635], [0.8122185804643189, 0.823497107247265, 0.8091660030231081, 0.7691860170638556, 0.8318323222026065, 0.8149526782858767], [0.774256656403223, 0.7918235880739435, 0.7684689978246045, 0.7622542291126118, 0.7580191047832017, 0.8202830457940575, 0.7810781169723617]]


In [ ]:
average_n = sum(maxima) / len(maxima)
print("average Design:",average_n)


average_base_all = []
for i in range(len(words_base_all)):
  average_base = sum(maxima_base_all[i]) / len(maxima_base_all[i])
  
  average_base_all.append(average_base)


average_n_front = sum(maxima_front) / len(maxima_front)
print("average FrontEnd:",average_n_front)

average_n_product = sum(maxima_product) / len(maxima_product)
print("average Product:",average_n_product)




print(average_base_all)

average Design: 0.7956341234362507
average FrontEnd: 0.8101421180478384
average Product: 0.7794548198520005
[0.7956341234362507, 0.8101421180478384, 0.7794548198520005]


In [ ]:
if (average_n>average_n_front and average_n>average_n_product):
  # Do nothing
  a = 1

if (average_n_front>average_n and average_n_front>average_n_product):
  scores = scores_front
  words_n_base = words_n_base_front

if (average_n_product>average_n and average_n_product>average_n_front):
  scores = scores_product
  words_n_base = words_n_base_product

In [ ]:
max_pos = scores.argmax(axis=1)

print(max_pos)

words_np = np.array(words_n)
print(max_pos)  
print(scores)
print("")
numberClose = 2
threshold = 0.6
for i in range(len(max_pos)):
  max_elements_position = np.argpartition(scores[i], -numberClose)[-numberClose:]
  print(max_elements_position)
  # print("Correlation = ",scores[i][max_elements_position])

  # scores_max_bigger_threshold = [number for number in scores[i][max_elements_position] if number > threshold]

  # scores_max_bigger_threshold = []
  # for number in scores[i][max_elements_position]:
  #   if number > threshold:
  #     scores_max_bigger_threshold.append(number)

  scores_max_bigger_threshold = []
  position_bigger_threshold = []
  for pos in max_elements_position:
    number = scores[i][pos]
    if number > threshold:
      scores_max_bigger_threshold.append(number)
      position_bigger_threshold.append(pos)

  # print("Correlation = " , scores_max_bigger_threshold)


  print("Base Knowledge Graph Name = ",words_n_base[i])
  print("Best word to connect = ",words_np[position_bigger_threshold])
  print("Correlation = ",scores[i][position_bigger_threshold])

  # print("Base Knowledge Graph Name = ",words_n_base[i])
  # print("Best word to connect = ",words_np[max_elements_position])
  # print("Correlation = ",scores[i][max_elements_position])


  # print("Base Knowledge Graph Name = ",words_n_base[i])
  # print("Best word to connect = ",words_n[max_pos[i]])
  # print("Correlation = ",scores[i][max_pos[i]])

[0 1 0 0 0 0]
[0 1 0 0 0 0]
[[0.81221858 0.7593976  0.76516075]
 [0.80072693 0.82349711 0.814047  ]
 [0.809166   0.77463429 0.78483933]
 [0.76918602 0.75809797 0.75549521]
 [0.83183232 0.77717363 0.77850659]
 [0.81495268 0.79219816 0.79277624]]

[2 0]
Base Knowledge Graph Name =  Frontend Developer
Best word to connect =  ['angular' ' node.js']
Correlation =  [0.76516075 0.81221858]
[2 1]
Base Knowledge Graph Name =  UI Implementation
Best word to connect =  ['angular' 'react']
Correlation =  [0.814047   0.82349711]
[2 0]
Base Knowledge Graph Name =  Frontend Architecture
Best word to connect =  ['angular' ' node.js']
Correlation =  [0.78483933 0.809166  ]
[1 0]
Base Knowledge Graph Name =  General Frontend Support
Best word to connect =  ['react' ' node.js']
Correlation =  [0.75809797 0.76918602]
[2 0]
Base Knowledge Graph Name =  Web Development
Best word to connect =  ['angular' ' node.js']
Correlation =  [0.77850659 0.83183232]
[2 0]
Base Knowledge Graph Name =  App Development
Bes

In [ ]:
prbest_k_ind = np.argpartition(scores, k) 
# best_k_ind = np.argpartition(scores, k)[-k:] 
print(best_k_ind)
top_k_emb = emb_mat[best_k_ind] 
# print(top_k_emb)

best_k_words = []
for i in range(len(best_k_ind)):
  best_k_words.append(words_n[best_k_ind[i]])

print(words_n[chooseWord])
print()
print(best_k_words)

ValueError: ignored

In [ ]:
# find the best connection of a word
w_e = 3
print("The word that we will search is: ",words_n[w_e])

print()
print()

max_n = 0
min_n = 1
w_p_max = -1 
w_p_min = -1
for i in range(len( resp['data'])):
  if (i!=w_e):
    cur = np.dot(words_embed[w_e], words_embed[i])
    # print(cur)
    if (cur>max_n):
      max_n = cur
      w_p_max = i

    if (cur<min_n):
      min_n = cur
      w_p_min = i


# print("The closest word has position: ",w_p_max, "\nis the word: ",words_n[w_p_max]," \nand has connection: ",max_n,)


print("WORD -> max: ",words_n[w_p_max])
print("Position -> max: ",w_p_max)
print("Correlation -> max: ",max_n)

print()

print("-----------------")

print()


print("WORD -> min: ",words_n[w_p_min])
print("Position -> min: ",w_p_min)
print("Correlation -> min: ",min_n)

The word that we will search is:  visual


WORD -> max:  design
Position -> max:  2
Correlation -> max:  0.8926727726446649

-----------------

WORD -> min:  Convolutional Neural Networks
Position -> min:  15
Correlation -> min:  0.7115761707971376


In [ ]:
np.dot(Javascript, Coding)

0.8778880869206246

In [ ]:
np.dot(Javascript, water)

0.7749276875681453

In [ ]:
np.dot(Javascript, object_t)

0.7993495038604859

In [ ]:
np.dot(embedding_a, embedding_c)

0.7891928072645734

In [ ]:
np.dot(embedding_c, embedding_d)

0.8543601927339739

In [ ]:
# https://www.kaggle.com/datasets/snap/amazon-fine-food-reviews
datafile_path = "https://cdn.openai.com/API/examples/data/fine_food_reviews_with_embeddings_1k.csv"  # for your convenience, we precomputed the embeddings
df = pd.read_csv(datafile_path)
df.head()

ProductId          UserId  Score  \
0  B003XPF9BO  A3R7JR3FMEBXQB      5   
1  B003JK537S  A3JBPC3WFUT5ZP      1   
2  B000JMBE7M   AQX1N6A51QOKG      4   
3  B004AHGBX4  A2UY46X0OSNVUQ      3   
4  B001BORBHO  A1AFOYZ9HSM2CZ      5   

                                             Summary  \
0  where does one  start...and stop... with a tre...   
1                                  Arrived in pieces   
2          It isn't blanc mange, but isn't bad . . .   
3        These also have SALT and it's not sea salt.   
4                             Happy with the product   

                                                Text  \
0  Wanted to save some to bring to my Chicago fam...   
1  Not pleased at all. When I opened the box, mos...   
2  I'm not sure that custard is really custard wi...   
3  I like the fact that you can see what you're g...   
4  My dog was suffering with itchy skin.  He had ...   

                                            combined  n_tokens  \
0  Title: where does one  start...and stop... wit...        51   
1  Title: Arrived in pieces; Content: Not pleased...        35   
2  Title: It isn't blanc mange, but isn't bad . ....       277   
3  Title: These also have SALT and it's not sea s...       246   
4  Title: Happy with the product; Content: My dog...        87   

                                  babbage_similarity  \
0  [-0.01274053193628788, 0.010849879123270512, -...   
1  [-0.024154752492904663, 0.0024838377721607685,...   
2  [0.0032693513203412294, 0.017815979197621346, ...   
3  [-0.03584608808159828, 0.03424076735973358, -0...   
4  [0.005218076519668102, 0.018165964633226395, -...   

                                      babbage_search  
0  [-0.01880764216184616, 0.019457539543509483, -...  
1  [-0.03571609780192375, 0.010356518439948559, -...  
2  [-0.010433986783027649, 0.024620095267891884, ...  
3  [-0.040209852159023285, 0.03804996609687805, -...  
4  [0.010450801812112331, 0.022801749408245087, -...

In [ ]:
type(df.loc[0]['babbage_search'])

str

In [ ]:
df["babbage_search"] = df.babbage_search.apply(eval).apply(np.array)
df["babbage_similarity"] = df.babbage_similarity.apply(eval).apply(np.array)


In [ ]:
type(df.loc[0]['babbage_search'])

numpy.ndarray

<h3>Semantic Search</h3>

In [ ]:
# search through the reviews for a specific product
def search_reviews(df, search_query, n=3):
    embedding = get_embedding(
        search_query,
        engine="text-search-babbage-query-001"
    )
    df["similarities"] = df.babbage_search.apply(lambda x: cosine_similarity(x, embedding))

    top_n =df.sort_values("similarities", ascending=False).head(n)
    # res = top_n.combined.str.replace("Title: ", "").str.replace("; Content:", ": ")
    return top_n

In [ ]:
res = search_reviews(df, "delicious beans", n=3)
res['combined'].to_list()

['Title: Fantastic Instant Refried beans; Content: Fantastic Instant Refried Beans have been a staple for my family now for nearly 20 years.  All 7 of us love it and my grown kids are passing on the tradition.',
 'Title: Jamaican Blue beans; Content: Excellent coffee bean for roasting. Our family just purchased another 5 pounds for more roasting. Plenty of flavor and mild on acidity when roasted to a dark brown bean and before any oil appears on the bean itself (455F @ 17 minutes).',
 "Title: Delicious!; Content: I enjoy this white beans seasoning, it gives a rich flavor to the beans I just love it, my mother in law didn't know about this Zatarain's brand and now she is traying different seasoning and she likes it very much.<br />Thank you Amazon for having it because now I can't find it in stores, I like to have this 12 boxes because I can made it whenever my family want it."]

<h3>Classification</h3>

In [ ]:
from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(
    list(df.babbage_similarity.values),
    df.Score,
    test_size = 0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
 
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
preds = clf.predict(X_test)

In [ ]:
print(classification_report(y_test,preds))

              precision    recall  f1-score   support

           1       0.62      0.72      0.67        18
           2       1.00      0.35      0.52        17
           3       0.50      0.12      0.20         8
           4       0.62      0.38      0.48        26
           5       0.83      0.98      0.90       131

    accuracy                           0.80       200
   macro avg       0.72      0.51      0.55       200
weighted avg       0.79      0.80      0.77       200



In [ ]:
len(df)

1000

In [ ]:
df['Score'].value_counts(normalize=True)

5    0.651
4    0.138
1    0.087
3    0.075
2    0.049
Name: Score, dtype: float64

<h3>Clustering</h3>

In [ ]:
# source: https://stackoverflow.com/questions/55619176/how-to-cluster-similar-sentences-using-bert
from sklearn.cluster import KMeans
# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]

In [ ]:
response = openai.Embedding.create(
    input=corpus,
    model="text-similarity-babbage-001"
)

In [ ]:
type(response['data'])

list

In [ ]:
# response['data'][0]['embedding']

In [ ]:
corpus_embeddings = [ d['embedding'] for d in response['data']]
# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [ ]:
clustering_model = KMeans(n_clusters=3)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[1 1 1 1 2 2 2 1 1 0 0 0 0 0 0]


In [ ]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{0: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.',
  'man and women with their baby are watching cheetah in zoo'],
 1: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'Horse is eating grass.',
  'A man is eating pasta.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.'],
 2: ['A Woman is eating Biryani.',
  'The girl is carrying a baby.',
  'The baby is carried by the woman']}

In [ ]:
clustering_model = KMeans(n_clusters=4)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[1 1 1 1 2 2 2 1 1 0 0 3 3 3 3]


In [ ]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{0: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.'],
 1: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'Horse is eating grass.',
  'A man is eating pasta.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.'],
 2: ['A Woman is eating Biryani.',
  'The girl is carrying a baby.',
  'The baby is carried by the woman'],
 3: ['A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.',
  'man and women with their baby are watching cheetah in zoo']}