<a href="https://colab.research.google.com/github/Soil-labs/Research-ML-knowledge-maping/blob/main/v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://openai.com/blog/introducing-text-and-code-embeddings/

In [1]:
!pip install openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 44 kB 2.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 147 kB 16.0 MB/s 
  Created wheel for openai: filename=openai-0.25.0-py3-none-any.whl size=55880 sha256=a03748cf8cca6dc4db7de143c537b89dff6cb95a4b68a1d049fea7a6a58043cd
  Stored in directory: /root/.cache/pip/wheels/4b/92/33/6f57c7aae0b16875267999a50570e81f15eecec577ebe05a2e
Successfully built openai


The **embedding is an information dense representation of the semantic meaning of a piece of text**. <br>
Each embedding is a vector of floating point numbers, such that the **distance between two embeddings in the vector space is correlated with semantic similarity between two inputs** in the original format. <br>
For example, if two texts are similar, then their vector representations should also be similar.

**Use cases:**

*   Text Similarity
*   Semantic Search
*   Classification
*   Clustering




1.   **Similarity embeddings** : These models are good at capturing semantic similarity between two or more pieces of text.
2.   **Text search embeddings**: These models help measure whether long documents are relevant to a short search query. There are two types: one for ***embedding the documents*** to be retrieved, and one for ***embedding the search query***.




In [2]:
import pandas as pd
import openai, numpy as np
from openai.embeddings_utils import get_embedding, cosine_similarity

In [3]:
api_key = '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'
openai.api_key = api_key


In [4]:
# text_search = "I start coding today, I love working on javascript but I want to be more structure with neo4j and now I will start working with convolutional neural networks togehter with Figma" # design
# text_search = "Yesterday I start working for the first time with Figma and Canva, it is great adition to my skills, can't wait to spent more time with tools except photoshop" # front
# text_search = "Finally I start working with a user research, we are trying to uderstand better the users, " #product
# text_search = "my dad left me at the age of 3 and now I have a separation anxiety" #nothing
# text_search = "I went ot the art school for 9 years" #design
# text_search = "I am a retire marine corps, and I have served on the front" #nothing
# text_search = "I start building a website, at age 8 now I am in google" # design # FrontEnd
# text_search = "I start photography but now I want to focus on buidling for companies" # design 
text_search = "I finally learned how to work with node.js but also I want to focus more on react and angular" # FrontEnd
# text_search = "I start learning hw to design websites, I use photoshop and I start drawingm circles" #design
# text_search = "there was so much snow that the flight didn't land but after all we met with my family and it was fun" #nothing



question_ask = "Extract keywords from this text:\n\n" + text_search + "\n\n Result:"

response = openai.Completion.create(
  model="text-davinci-003",
  prompt=question_ask,
  temperature=0.5,
  max_tokens=60,
  top_p=1,
  frequency_penalty=0.8,
  presence_penalty=0
)



In [5]:
print(response["choices"][0]["text"])



node.js, react, angular


<h3>Text Similarity</h3>

In [14]:
# words_n = ["Neo4j","react","next.js","Figma","design","visual","graphic","art", "Javascript", "Coding" ,"CNN", "react","water","object","Convolutional Neural Networks","Machine Learning","cherry","pie"]
words_n = response["choices"][0]["text"].split(', ')
resp = openai.Embedding.create(
    input=words_n,
    engine="text-similarity-davinci-001")


# words_n_base = ["UI Design"]
words_n_base = ["Design","UX/UI","Graphic Design","Web Design","Game Design","Animation","General Design support from A-Z","NFT Design","Brand Design"]
resp_base = openai.Embedding.create(
    input=words_n_base,
    engine="text-similarity-davinci-001")


words_n_base_front = ["Frontend Developer","UI Implementation","Frontend Architecture","General Frontend Support","Web Development","App Development"]
resp_base_front = openai.Embedding.create(
    input=words_n_base_front,
    engine="text-similarity-davinci-001")


words_n_base_product = ["Product Manager","User Research","Market Research","Technical Team Coordination","Design Team Coordination","Ideation","Interviews"]
resp_base_product = openai.Embedding.create(
    input=words_n_base_product,
    engine="text-similarity-davinci-001")


words_n_all = []
words_n_all.append(words_n_base)
words_n_all.append(words_n_base_front)
words_n_all.append(words_n_base_front)

In [15]:
words_embed = []
for i in range(len( resp['data'])):
  words_embed.append(resp['data'][i]['embedding'])


words_embed_base = []
for i in range(len( resp_base['data'])):
  words_embed_base.append(resp_base['data'][i]['embedding'])


words_embed_base_front = []
for i in range(len( resp_base_front['data'])):
  words_embed_base_front.append(resp_base_front['data'][i]['embedding'])


words_embed_base_product = []
for i in range(len( resp_base_product['data'])):
  words_embed_base_product.append(resp_base_product['data'][i]['embedding'])


words_base_all = []
words_base_all.append(words_embed_base)
words_base_all.append(words_embed_base_front)
words_base_all.append(words_embed_base_product)

# print(words_base_all[1])
# print(words_embed_base_front)

In [16]:
k = 10 # k best embeddings
emb_mat = np.stack(words_embed)
# print(emb_mat)

emb_mat_base_all = []
for i in range(len(words_base_all)):
  emb_mat_base = np.stack(words_base_all[i])
  
  emb_mat_base_all.append(emb_mat_base)


emb_mat_base = np.stack(words_embed_base)
# print(emb_mat_base)


emb_mat_base_front = np.stack(words_embed_base_front)
# print(emb_mat_base_front)

emb_mat_base_product = np.stack(words_embed_base_product)
# print(emb_mat_base_product)


In [17]:
chooseWord = 3
scores = np.dot(emb_mat_base,emb_mat.T)
# scores = np.dot(emb_mat,emb_mat_base.T)
print(scores)


scores_base_all = []
for i in range(len(words_base_all)):
  scores_base = np.dot(emb_mat_base_all[i],emb_mat.T)
  
  scores_base_all.append(scores_base)


scores_front = np.dot(emb_mat_base_front,emb_mat.T)


print()
print()

print(scores_front)


scores_product = np.dot(emb_mat_base_product,emb_mat.T)


print()
print()

print(scores_product)

[[0.76578132 0.83401948 0.83865283]
 [0.78244649 0.81227447 0.80754811]
 [0.75696196 0.76545913 0.77118749]
 [0.79935827 0.78208007 0.78191594]
 [0.78141215 0.79285492 0.79375412]
 [0.78391109 0.83769334 0.83037538]
 [0.7210471  0.70193232 0.69224291]
 [0.78238383 0.7842773  0.78352532]
 [0.77036025 0.8122506  0.80716802]]


[[0.8086257  0.76054106 0.76337418]
 [0.80944652 0.82348674 0.81145058]
 [0.81718861 0.77738603 0.78413234]
 [0.78341721 0.75856752 0.75249162]
 [0.82747576 0.77753399 0.77455082]
 [0.81228519 0.78980126 0.78717936]]


[[0.76814859 0.76313447 0.75750518]
 [0.7856003  0.79001378 0.7698769 ]
 [0.76696649 0.77229188 0.76144647]
 [0.7747524  0.751466   0.74593608]
 [0.76080362 0.75893328 0.75007299]
 [0.76844286 0.82414519 0.81413349]
 [0.77165414 0.77984377 0.77985902]]


In [18]:
maxima = list(map(max, scores))
print(maxima)  # Output: [3, 6, 9]

maxima_base_all = []
for i in range(len(words_base_all)):
  maxima_base = list(map(max, scores_base_all[i]))
  
  maxima_base_all.append(maxima_base)


maxima_front = list(map(max, scores_front))
print(maxima_front)  # Output: [3, 6, 9]

maxima_product = list(map(max, scores_product))
print(maxima_product)  # Output: [3, 6, 9]


print(maxima_base_all)

[0.8386528297724409, 0.8122744723271862, 0.7711874892827058, 0.7993582653380178, 0.7937541152594048, 0.8376933389284876, 0.7210471043191763, 0.7842772957201889, 0.8122506044192864]
[0.8086257043868713, 0.8234867397838965, 0.8171886081055226, 0.7834172130793375, 0.8274757599086624, 0.8122851896801885]
[0.768148593397363, 0.7900137834096558, 0.7722918809946744, 0.7747523984526041, 0.7608036175541735, 0.8241451947115287, 0.7798590247500595]
[[0.8386528297724409, 0.8122744723271862, 0.7711874892827058, 0.7993582653380178, 0.7937541152594048, 0.8376933389284876, 0.7210471043191763, 0.7842772957201889, 0.8122506044192864], [0.8086257043868713, 0.8234867397838965, 0.8171886081055226, 0.7834172130793375, 0.8274757599086624, 0.8122851896801885], [0.768148593397363, 0.7900137834096558, 0.7722918809946744, 0.7747523984526041, 0.7608036175541735, 0.8241451947115287, 0.7798590247500595]]


In [19]:
average_n = sum(maxima) / len(maxima)
print("average Design:",average_n)


average_base_all = []
for i in range(len(words_base_all)):
  average_base = sum(maxima_base_all[i]) / len(maxima_base_all[i])
  
  average_base_all.append(average_base)


average_n_front = sum(maxima_front) / len(maxima_front)
print("average FrontEnd:",average_n_front)

average_n_product = sum(maxima_product) / len(maxima_product)
print("average Product:",average_n_product)




print(average_base_all)

average Design: 0.796721723929655
average FrontEnd: 0.8120798691574133
average Product: 0.7814306418957228
[0.796721723929655, 0.8120798691574133, 0.7814306418957228]


In [23]:
# python find the position of the bigger number on the array called average_base_all
pos_knowGr = average_base_all.index(max(average_base_all))
print("The position of the bigger number is:", pos_knowGr)
scores = scores_base_all[pos_knowGr]
words_n_base = words_n_all[pos_knowGr]



# if (average_n>average_n_front and average_n>average_n_product):
#   # Do nothing
#   a = 1

# if (average_n_front>average_n and average_n_front>average_n_product):
#   scores = scores_front
#   words_n_base = words_n_base_front

# if (average_n_product>average_n and average_n_product>average_n_front):
#   scores = scores_product
#   words_n_base = words_n_base_product

The position of the bigger number is: 1


In [24]:
max_pos = scores.argmax(axis=1)

print(max_pos)

words_np = np.array(words_n)
print(max_pos)  
print(scores)
print("")
numberClose = 2
threshold = 0.6
for i in range(len(max_pos)):
  max_elements_position = np.argpartition(scores[i], -numberClose)[-numberClose:]
  print(max_elements_position)
  # print("Correlation = ",scores[i][max_elements_position])

  # scores_max_bigger_threshold = [number for number in scores[i][max_elements_position] if number > threshold]

  # scores_max_bigger_threshold = []
  # for number in scores[i][max_elements_position]:
  #   if number > threshold:
  #     scores_max_bigger_threshold.append(number)

  scores_max_bigger_threshold = []
  position_bigger_threshold = []
  for pos in max_elements_position:
    number = scores[i][pos]
    if number > threshold:
      scores_max_bigger_threshold.append(number)
      position_bigger_threshold.append(pos)

  # print("Correlation = " , scores_max_bigger_threshold)


  print("Base Knowledge Graph Name = ",words_n_base[i])
  print("Best word to connect = ",words_np[position_bigger_threshold])
  print("Correlation = ",scores[i][position_bigger_threshold])

  # print("Base Knowledge Graph Name = ",words_n_base[i])
  # print("Best word to connect = ",words_np[max_elements_position])
  # print("Correlation = ",scores[i][max_elements_position])


  # print("Base Knowledge Graph Name = ",words_n_base[i])
  # print("Best word to connect = ",words_n[max_pos[i]])
  # print("Correlation = ",scores[i][max_pos[i]])

[0 1 0 0 0 0]
[0 1 0 0 0 0]
[[0.8086257  0.76054106 0.76337418]
 [0.80944652 0.82348674 0.81145058]
 [0.81718861 0.77738603 0.78413234]
 [0.78341721 0.75856752 0.75249162]
 [0.82747576 0.77753399 0.77455082]
 [0.81228519 0.78980126 0.78717936]]

[2 0]
Base Knowledge Graph Name =  Frontend Developer
Best word to connect =  ['angular' '\n\nnode.js']
Correlation =  [0.76337418 0.8086257 ]
[2 1]
Base Knowledge Graph Name =  UI Implementation
Best word to connect =  ['angular' 'react']
Correlation =  [0.81145058 0.82348674]
[2 0]
Base Knowledge Graph Name =  Frontend Architecture
Best word to connect =  ['angular' '\n\nnode.js']
Correlation =  [0.78413234 0.81718861]
[1 0]
Base Knowledge Graph Name =  General Frontend Support
Best word to connect =  ['react' '\n\nnode.js']
Correlation =  [0.75856752 0.78341721]
[1 0]
Base Knowledge Graph Name =  Web Development
Best word to connect =  ['react' '\n\nnode.js']
Correlation =  [0.77753399 0.82747576]
[1 0]
Base Knowledge Graph Name =  App Devel

<h3>Clustering</h3>