<a href="https://colab.research.google.com/github/Soil-labs/Research-ML-knowledge-maping/blob/main/v4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://openai.com/blog/introducing-text-and-code-embeddings/

In [ ]:
!pip install openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


The **embedding is an information dense representation of the semantic meaning of a piece of text**. <br>
Each embedding is a vector of floating point numbers, such that the **distance between two embeddings in the vector space is correlated with semantic similarity between two inputs** in the original format. <br>
For example, if two texts are similar, then their vector representations should also be similar.

**Use cases:**

*   Text Similarity
*   Semantic Search
*   Classification
*   Clustering




1.   **Similarity embeddings** : These models are good at capturing semantic similarity between two or more pieces of text.
2.   **Text search embeddings**: These models help measure whether long documents are relevant to a short search query. There are two types: one for ***embedding the documents*** to be retrieved, and one for ***embedding the search query***.




In [ ]:
import pandas as pd
import openai, numpy as np
from openai.embeddings_utils import get_embedding, cosine_similarity

In [ ]:
api_key = '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'
openai.api_key = api_key


In [ ]:
# text_search = "I start coding today, I love working on javascript but I want to be more structure with neo4j and now I will start working with convolutional neural networks togehter with Figma" # design
# text_search = "Yesterday I start working for the first time with Figma and Canva, it is great adition to my skills, can't wait to spent more time with tools except photoshop" # front
# text_search = "Finally I start working with a user research, we are trying to uderstand better the users, " #product
# text_search = "my dad left me at the age of 3 and now I have a separation anxiety" #nothing
# text_search = "I went ot the art school for 9 years" #design
# text_search = "I am a retire marine corps, and I have served on the front" #nothing
# text_search = "I start building a website, at age 8 now I am in google" # design # FrontEnd
# text_search = "I start photography but now I want to focus on buidling for companies" # design 
text_search = "I finally learned how to work with node.js but also I want to focus more on react and angular" # FrontEnd
# text_search = "I start learning hw to design websites, I use photoshop and I start drawingm circles" #design
# text_search = "there was so much snow that the flight didn't land but after all we met with my family and it was fun" #nothing



question_ask = "Extract keywords from this text:\n\n" + text_search + "\n\n Result:"

response = openai.Completion.create(
  model="text-davinci-003",
  prompt=question_ask,
  temperature=0.5,
  max_tokens=60,
  top_p=1,
  frequency_penalty=0.8,
  presence_penalty=0
)



In [ ]:
print(response["choices"][0]["text"])


node.js, react, angular


<h3>Text Similarity</h3>

In [ ]:
# words_n = ["Neo4j","react","next.js","Figma","design","visual","graphic","art", "Javascript", "Coding" ,"CNN", "react","water","object","Convolutional Neural Networks","Machine Learning","cherry","pie"]
words_n = response["choices"][0]["text"].split(', ')
resp = openai.Embedding.create(
    input=words_n,
    engine="text-similarity-davinci-001")


# words_n_base = ["UI Design"]
words_n_base = ["Design","UX/UI","Graphic Design","Web Design","Game Design","Animation","General Design support from A-Z","NFT Design","Brand Design"]
resp_base = openai.Embedding.create(
    input=words_n_base,
    engine="text-similarity-davinci-001")


words_n_base_front = ["Frontend Developer","UI Implementation","Frontend Architecture","General Frontend Support","Web Development","App Development"]
resp_base_front = openai.Embedding.create(
    input=words_n_base_front,
    engine="text-similarity-davinci-001")


words_n_base_product = ["Product Manager","User Research","Market Research","Technical Team Coordination","Design Team Coordination","Ideation","Interviews"]
resp_base_product = openai.Embedding.create(
    input=words_n_base_product,
    engine="text-similarity-davinci-001")

In [ ]:
words_embed = []
for i in range(len( resp['data'])):
  words_embed.append(resp['data'][i]['embedding'])


words_embed_base = []
for i in range(len( resp_base['data'])):
  words_embed_base.append(resp_base['data'][i]['embedding'])


words_embed_base_front = []
for i in range(len( resp_base_front['data'])):
  words_embed_base_front.append(resp_base_front['data'][i]['embedding'])


words_embed_base_product = []
for i in range(len( resp_base_product['data'])):
  words_embed_base_product.append(resp_base_product['data'][i]['embedding'])


words_base_all = []
words_base_all.append(words_embed_base)
words_base_all.append(words_embed_base_front)
words_base_all.append(words_embed_base_product)

# print(words_base_all[1])
# print(words_embed_base_front)

In [ ]:
k = 10 # k best embeddings
emb_mat = np.stack(words_embed)
# print(emb_mat)

emb_mat_base_all = []
for i in range(len(words_base_all)):
  emb_mat_base = np.stack(words_base_all[i])
  
  emb_mat_base_all.append(emb_mat_base)


emb_mat_base = np.stack(words_embed_base)
# print(emb_mat_base)


emb_mat_base_front = np.stack(words_embed_base_front)
# print(emb_mat_base_front)

emb_mat_base_product = np.stack(words_embed_base_product)
# print(emb_mat_base_product)


In [ ]:
chooseWord = 3
scores = np.dot(emb_mat_base,emb_mat.T)
# scores = np.dot(emb_mat,emb_mat_base.T)
print(scores)


scores_base_all = []
for i in range(len(words_base_all)):
  scores_base = np.dot(emb_mat_base_all[i],emb_mat.T)
  
  scores_base_all.append(scores_base)


scores_front = np.dot(emb_mat_base_front,emb_mat.T)


print()
print()

print(scores_front)


scores_product = np.dot(emb_mat_base_product,emb_mat.T)


print()
print()

print(scores_product)

[[0.76279171 0.83401948 0.83865283]
 [0.78022329 0.81030721 0.80519608]
 [0.75440394 0.76638343 0.77179573]
 [0.79910941 0.78289732 0.78273399]
 [0.77845498 0.79281564 0.79392095]
 [0.77922495 0.83974771 0.83223032]
 [0.71362989 0.70414817 0.69448642]
 [0.77522274 0.78325974 0.78199894]
 [0.76497504 0.81312547 0.80776582]]


[[0.80853791 0.76054106 0.76337418]
 [0.80490882 0.82467176 0.81233741]
 [0.81012065 0.77669975 0.78343402]
 [0.77609293 0.7612373  0.75532717]
 [0.83281243 0.77754544 0.77522225]
 [0.81659532 0.79188512 0.79017915]]


[[0.77001377 0.76313447 0.75750518]
 [0.7817497  0.79008274 0.77041588]
 [0.76082761 0.77158018 0.7608833 ]
 [0.76866889 0.75028094 0.74556521]
 [0.75235787 0.75817844 0.74889661]
 [0.76545487 0.81976373 0.80888975]
 [0.77467232 0.78254959 0.78292756]]


In [ ]:
maxima = list(map(max, scores))
print(maxima)  # Output: [3, 6, 9]

maxima_base_all = []
for i in range(len(words_base_all)):
  maxima_base = list(map(max, scores_base_all[i]))
  
  maxima_base_all.append(maxima_base)


maxima_front = list(map(max, scores_front))
print(maxima_front)  # Output: [3, 6, 9]

maxima_product = list(map(max, scores_product))
print(maxima_product)  # Output: [3, 6, 9]


print(maxima_base_all)

[0.8386528297724409, 0.8103072146402821, 0.7717957340136551, 0.799109405254009, 0.7939209541344174, 0.8397477060506124, 0.7136298907372705, 0.7832597356811399, 0.8131254703378511]
[0.8085379106371029, 0.8246717628717523, 0.8101206461421753, 0.7760929312606785, 0.832812434831967, 0.8165953158013728]
[0.770013765039608, 0.790082735335573, 0.7715801835470645, 0.7686688925536842, 0.758178437281094, 0.8197637320833042, 0.7829275611542176]
[[0.8386528297724409, 0.8103072146402821, 0.7717957340136551, 0.799109405254009, 0.7939209541344174, 0.8397477060506124, 0.7136298907372705, 0.7832597356811399, 0.8131254703378511], [0.8085379106371029, 0.8246717628717523, 0.8101206461421753, 0.7760929312606785, 0.832812434831967, 0.8165953158013728], [0.770013765039608, 0.790082735335573, 0.7715801835470645, 0.7686688925536842, 0.758178437281094, 0.8197637320833042, 0.7829275611542176]]


In [ ]:
average_n = sum(maxima) / len(maxima)
print("average Design:",average_n)


average_base_all = []
for i in range(len(words_base_all)):
  average_base = sum(maxima_base_all[i]) / len(maxima_base_all[i])
  
  average_base_all.append(average_base)


average_n_front = sum(maxima_front) / len(maxima_front)
print("average FrontEnd:",average_n_front)

average_n_product = sum(maxima_product) / len(maxima_product)
print("average Product:",average_n_product)




print(average_base_all)

average Design: 0.7959498822912976
average FrontEnd: 0.8114718335908416
average Product: 0.7801736152849349
[0.7959498822912976, 0.8114718335908416, 0.7801736152849349]


In [ ]:
if (average_n>average_n_front and average_n>average_n_product):
  # Do nothing
  a = 1

if (average_n_front>average_n and average_n_front>average_n_product):
  scores = scores_front
  words_n_base = words_n_base_front

if (average_n_product>average_n and average_n_product>average_n_front):
  scores = scores_product
  words_n_base = words_n_base_product

In [ ]:
max_pos = scores.argmax(axis=1)

print(max_pos)

words_np = np.array(words_n)
print(max_pos)  
print(scores)
print("")
numberClose = 2
threshold = 0.6
for i in range(len(max_pos)):
  max_elements_position = np.argpartition(scores[i], -numberClose)[-numberClose:]
  print(max_elements_position)
  # print("Correlation = ",scores[i][max_elements_position])

  # scores_max_bigger_threshold = [number for number in scores[i][max_elements_position] if number > threshold]

  # scores_max_bigger_threshold = []
  # for number in scores[i][max_elements_position]:
  #   if number > threshold:
  #     scores_max_bigger_threshold.append(number)

  scores_max_bigger_threshold = []
  position_bigger_threshold = []
  for pos in max_elements_position:
    number = scores[i][pos]
    if number > threshold:
      scores_max_bigger_threshold.append(number)
      position_bigger_threshold.append(pos)

  # print("Correlation = " , scores_max_bigger_threshold)


  print("Base Knowledge Graph Name = ",words_n_base[i])
  print("Best word to connect = ",words_np[position_bigger_threshold])
  print("Correlation = ",scores[i][position_bigger_threshold])

  # print("Base Knowledge Graph Name = ",words_n_base[i])
  # print("Best word to connect = ",words_np[max_elements_position])
  # print("Correlation = ",scores[i][max_elements_position])


  # print("Base Knowledge Graph Name = ",words_n_base[i])
  # print("Best word to connect = ",words_n[max_pos[i]])
  # print("Correlation = ",scores[i][max_pos[i]])

[0 1 0 0 0 0]
[0 1 0 0 0 0]
[[0.80853791 0.76054106 0.76337418]
 [0.80490882 0.82467176 0.81233741]
 [0.81012065 0.77669975 0.78343402]
 [0.77609293 0.7612373  0.75532717]
 [0.83281243 0.77754544 0.77522225]
 [0.81659532 0.79188512 0.79017915]]

[2 0]
Base Knowledge Graph Name =  Frontend Developer
Best word to connect =  ['angular' '\nnode.js']
Correlation =  [0.76337418 0.80853791]
[2 1]
Base Knowledge Graph Name =  UI Implementation
Best word to connect =  ['angular' 'react']
Correlation =  [0.81233741 0.82467176]
[2 0]
Base Knowledge Graph Name =  Frontend Architecture
Best word to connect =  ['angular' '\nnode.js']
Correlation =  [0.78343402 0.81012065]
[1 0]
Base Knowledge Graph Name =  General Frontend Support
Best word to connect =  ['react' '\nnode.js']
Correlation =  [0.7612373  0.77609293]
[1 0]
Base Knowledge Graph Name =  Web Development
Best word to connect =  ['react' '\nnode.js']
Correlation =  [0.77754544 0.83281243]
[1 0]
Base Knowledge Graph Name =  App Development
B

In [ ]:
prbest_k_ind = np.argpartition(scores, k) 
# best_k_ind = np.argpartition(scores, k)[-k:] 
print(best_k_ind)
top_k_emb = emb_mat[best_k_ind] 
# print(top_k_emb)

best_k_words = []
for i in range(len(best_k_ind)):
  best_k_words.append(words_n[best_k_ind[i]])

print(words_n[chooseWord])
print()
print(best_k_words)

ValueError: ignored

<h3>Clustering</h3>